services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports: ["5432:5432"]

  backend:
    build: ./backend
    image: mp3-fullstack-backend:local
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: app
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: mp3-fullstack-frontend:local

  proxy:
    build: ./proxy
    image: mp3-fullstack-proxy:local
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
